!!setting.ConfigSetting
compressFileList: null
excludeFilePathList: [node_modules, $RECYCLE.BIN, Program Files, Windows]
fileList: [docx, doc, xls, xlsx, pdf, txt]
hasCreateIndex: true
inputDataPath: ['C:\Users\neal1\project\lucene-test\test-data']
searchMethod: F
